### ISSUE TITLE
Stratum, `/opt/usr/lib` and Library Path

### ISSUE THREAD

**Issue by CommitThis** [NetworkGradeLinux/meta-mion#120]
When starting Stratum, it is unable to launch the SDE because the libraries it requires are not in the library path. These libraries are located in `/opt/usr/lib` which I believe to be added by Stratum, i.e., these libraries have the same names as those that would otherwise be installed via the SDE.

If there are no conflicts it may be worth adding this path to `/etc/ld.so.conf/stratum.conf`. However, conflicts, if any, should be figured out before doing so.

**Comment by toganlabs** [comment]
Fixed in https://github.com/NetworkGradeLinux/meta-mion-stratum/commit/4397f3ac069545a2e0d31bdd3ccb5c07bf76acf8
