### ISSUE TITLE
Investigate package management for qemu image

### ISSUE THREAD

**Issue by kprosise** [NetworkGradeLinux/meta-mion#124]
On qemu, http://tilde.toganlabs.com/repo/2021.03/qemux86_64/Packages.gz doesn't exist. No problems with the other qemu repos however.

Related, we should decide if package management is relevant or note for the qemu image.

**Comment by kprosise** [comment]
During qemu purpose and functionality discussion, it was decided that package management on qemu is something we want.

**Comment by johntoomey** [comment]
looks like the package manager stuff is already present on the qemu image so all thats needed is the packages to be created nightly - i have added this to the CI so will wait until tomorrow to see if its working correctly https://github.com/NetworkGradeLinux/mion-ci/compare/008276158184...e4456430b364

**Comment by johntoomey** [comment]
this appears to be working now - closing
