### ISSUE TITLE
Switchdev implementation - core-bsb and stordis

### ISSUE THREAD

**Issue by johntoomey** [NetworkGradeLinux/meta-mion#20]

**Comment by N-Mc-Nally** [comment]
@toganlabs - @CommitThis raised question about this piece also, would like more info.

**Comment by toganlabs** [comment]
Waiting for https://github.com/NetworkGradeLinux/meta-mion-bsp/issues/9

**Comment by toganlabs** [comment]
Defconfig with switchdev patches included here https://github.com/NetworkGradeLinux/meta-mion-bsp/commit/1f490c9552f38641377cea8078c87ae35c0c4bac
