### ISSUE TITLE
Fix Deferred Tasks

### ISSUE THREAD

**Issue by toganlabs** [NetworkGradeLinux/meta-mion#29]
During the initial build, bitbake drops into single thread for a bunch of do_fetches.

I've tracked this down to how we fixed the race condition in the -pkg recipes which require the container to have been built before we do_image the host.

I'm still debugging this and have an email into Scott Murray to see if he has any ideas, but I've at least root caused this. The solution here might be to simplify the container builds some but we do lose some functionality in doing that.

**Comment by johntoomey** [comment]
fixed here: https://github.com/NetworkGradeLinux/meta-mion/commit/2b0c41da6730b54a9e7a6ae397cacdba18c3e7eb
