### ISSUE TITLE
Explore alternative container runtime - containerd

### ISSUE THREAD

**Issue by johntoomey** [NetworkGradeLinux/meta-mion#33]

**Comment by johntoomey** [comment]
Details outlined [on the wiki](https://github.com/NetworkGradeLinux/mion-docs/wiki/Mion-container-runtime), comments and additions would be greatly appreciated!

Potentially useful information - brain dump:
- https://containerd.io/docs/getting-started/
- https://github.com/projectatomic/containerd/blob/master/docs/cli.md
- https://sweetcode.io/getting-started-with-containerd/
- https://stackoverflow.com/questions/59393496/how-to-run-docker-images-in-containerd-using-ctr-in-cli
- https://blog.savoirfairelinux.com/en-ca/2020/how-to-embed-a-docker-image-into-yoctos-root-filesystem/

Note that the kernel config currently appears to be missing the module-xt-addrtype option which is required for Docker to work correctly, and potentially others. 
- https://git.yoctoproject.org/cgit/cgit.cgi/meta-virtualization/commit/?id=8860257250e85fd6c963bebc0f9004bbd0b27a0b

**Comment by johntoomey** [comment]
Discussed with Sinead - she is going to solicit feedback from the community and come back with a recommendation

**Comment by ishidawataru** [comment]
Goldstone uses `k3s` as the container orchestrator. `k3s` uses `containerd` internally for the container runtime.

[`k3s` supports air-gap environment](https://rancher.com/docs/k3s/latest/en/installation/airgap/) and Goldstone uses that feature.

Goldstone build system puts all container images under `/var/lib/rancher/k3s/agent/images` like [here](https://github.com/Telecominfraproject/oopt-goldstone/blob/master/packages/base/amd64/tai/PKG.yml#L14) and let k3s load it to local container image storage.

Since this is a waste of storage space, it would be nice if NGL build system can build a rootfs with the container images already stored in the local container image storage.

containerd is the de facto container runtime and I think this will be choice if NGL decides to introduce any container runtime.

Since `containerd` was not intended to controlled directly by human, the usability was one of the downside compared with `docker`.
However, that can be solved by using [nerdctl](https://github.com/containerd/nerdctl).

**Comment by johntoomey** [comment]
@ishidawataru @N-Mc-Nally @toganlabs 

ok - we have started working on the assumption that we are going to replace the current (limited) container solution with something based on k3s. as k3s is not available in meta-virtualisation dunfell branch we have back-ported it to [meta-mion-backports](https://github.com/NetworkGradeLinux/meta-mion-backports) but its not really clear how we should test this.

the next steps are to start looking at how this will be used in the real world and if we can easily support the airgapped container use case. According to the docker and containerd docs it is possible to save an image to a tar archive and dump it in a known location for k3s to install and run on boot but we need to test to make sure this actually works as expected.

Comments welcome!!!

**Comment by ishidawataru** [comment]
@johntoomey Saving containers to tar archive is easy and the k3s airgap feature works fine.

I'm applying small patches to k3s to make it work in a totally no-network environment. The vanilla k3s doesn't work in an airgap environment where no ethernet link is up and no default gateway available. Also, it is assumed that the clock is properly configured and stable and DNS server is configured ( reachability is not required though )

IMHO, putting only contained in mion is a better first step. k3s supports using external containerd. After integrating containerd, we can integrate k3s as an option for container management. ( though it looks like there is some issue with external containerd feature + airgap feature : https://github.com/k3s-io/k3s/issues/3100 )

**Comment by johntoomey** [comment]
Ok - so - here is the plan: @toganlabs @kprosise @ishidawataru @N-Mc-Nally 

There is no way to pick a container solution that will be agreeable to everyone so my suggestion is that we have the minimum viable product - this is ContainerD+runc.

- we need to decide if this is installed in the default image or in its own image - i suggest that if it doesnt add much in terms of size and compile time and the containerd service is disabled by default then we just add it to the default image so that it can be used to make sure the container stack is actually working (kernel modules etc)
- I have tested the ability of containerd to install and runn "air-gapped" images, created using ```docker save``` (all container runtimes seem to have equivalent functionality for saving images) and imported/run on the switch and it appears to work - if there is a strong desire to build this sort of thing into build system we can explore this but knowing that it works is enough for now IMO
- I have time booked with @toganlabs to remove meta-mion-srunc and as much of the tooling around this functionality as we can reasonably next week - this should result in a simpler, more maintainable mion (lower barrier for entry for new users)
- We will keep the k3s backport which appears to be working but we will not put a huge amount of effort into maintaining it if it is not being actively used. Similarly - docker, podman and the other container tooling in meta-virt is either working or mostly working and we can support it if there is a request from the community.

If this all goes through - the next release will have simple but working, secure and maintainable container functionality which we can build on in the future as desired.

**Comment by johntoomey** [comment]
- https://blog.scottlowe.org/2020/01/25/manually-loading-container-images-with-containerd/
- https://github.com/opencontainers/runtime-spec/blob/master/bundle.md
- https://iximiuz.com/en/posts/you-dont-need-an-image-to-run-a-container/

**Comment by johntoomey** [comment]
Ok - im going to call this one done for now - here is the summary of what we did
- purged srunc from the system (moved to unsupported) 
- removed the dependency on multiconfig added a new build script (cronie.sh) which doesnt use multiconfig
- added containerd and runc to the base image - i think the service is disabled by default
- k3s added to a new layer meta-mion-backports - appears to work but is not installed by default

There are some breaking changes in here - build script and layers - so well need to take extra care to update the associated documentation (@kprosise) on this one
