### ISSUE TITLE
Add p4 accounts with BF SDE recipe and document how to add/mod accounts at build time

### ISSUE THREAD

**Issue by johntoomey** [NetworkGradeLinux/meta-mion#62]
Activate passwordless wheel in sudoers
  %wheel ALL=(ALL) NOPASSWD: ALL                                                       
Comment out the line in sudoers:
Defaults secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
add p4 to wheel 
 useradd -m -G wheel -s /bin/bash p4
and create a /etc/profiles.d. 
Mkdir /etc/profile.d
Add a default password to root / password m10n
Add p4 user account with p4 password

**Comment by toganlabs** [comment]
Some of this exists in documentation already and @kprosise should document how to add/mod users/add env vars.

For p4 issues, this is part of the SDE recipe which I'll deal with.

**Comment by johntoomey** [comment]
This is already documented in the [yocto project](https://git.yoctoproject.org/cgit.cgi/poky/tree/meta-skeleton/recipes-skeleton/useradd/useradd-example.bb) so we are closing this as it is not going to be added to the image
