### ISSUE TITLE
Test and document the oldest version of ONIE which is supported

### ISSUE THREAD

**Issue by johntoomey** [NetworkGradeLinux/meta-mion#63]
we are only going to support new(ish) versions of onie at the moment - pick a version in the last year or so and test it on the wedge, if it installs ok thats the oldest version we support..

**Comment by johntoomey** [comment]
so, i cant actually test this because it would require access to a Wedge100 which i dont have and would take maybe half a day to test a number of versions until i found the oldest one that worked. 

Instead i have opted to make it clear in the Installation section of the documentation that a recent version of ONIE is required and older versions may cause issues https://github.com/NetworkGradeLinux/mion-docs/pull/244

Assigning to @kprosise for approval - feel free to just take my pull request as a suggestion/starting point if you want to say this in a different way!

**Comment by kprosise** [comment]
Changes made by @johntoomey applied after some minor style guide changes were applied in [mion-docs PR 245](https://github.com/NetworkGradeLinux/mion-docs/pull/245). closing issue.
