### ISSUE TITLE
MION_BUILD_ID not set

### ISSUE THREAD

**Issue by gerritavenant** [NetworkGradeLinux/meta-mion#65]
https://github.com/NetworkGradeLinux/meta-mion/blob/5dca40266a5f887b3e25561778782a0d68986156/meta-mion/recipes-core/os-release/os-release.bbappend#L12

Minor issue, it does not look like the `${MION_BUILD_ID}` gets passed through anywhere - maybe also via `mc_build.sh` with a default value if nothing is specified?

**Comment by toganlabs** [comment]
Fixed in https://github.com/NetworkGradeLinux/meta-mion/commit/a4ade7660b445b08165d1c532ed13fcfa188d65c
