### ISSUE TITLE
onlpdump systemd service not working

### ISSUE THREAD

**Issue by alexandergall** [NetworkGradeLinux/meta-mion#67]
The `onlpdump.service` fails with

```
Jan 08 14:47:46 accton-wedge100bf-32x systemd[3805]: onlpdump.service: Failed to execute command: No such file or directory
Jan 08 14:47:46 accton-wedge100bf-32x systemd[3805]: onlpdump.service: Failed at step EXEC spawning /usr/bin/onlpdump: No such file or directory
```
There is a Python script `/usr/bin/onlpdump/py`, but that is non-functional due to a missing `libonlp.so`.

**Comment by kprosise** [comment]
@alexandergall, thank you for reporting!

 I believe there's sufficient information to reproduce, however for clarity, if you could provide the commit hashes of `meta-mion` and `meta-mion-bsp` used to build, that would be great! There may be a request for more information early next week when the maintainers return.

if you haven't already,  feel free to get in touch with us on [slack](https://join.slack.com/t/networkgradelinux/shared_invite/zt-ktyqftox-yFOV8a7qdgDVvPADkc82tw)!

**Comment by alexandergall** [comment]
I'm using `dunfell-2020.12` for both

`meta-mion`: `5dca4026`
`meta-mion-bsp`: `30f2347c`

**Comment by toganlabs** [comment]
This is most likely an issue with ONLPv1 do_install()

**Comment by kprosise** [comment]
A number of  libonlp links are not making it into the final image.  Adding `dev-pkgs` fixes this, however onlpdump.py will need to be tested.  A PR will be opened which adds dev-pkgs to mion.

**Comment by kprosise** [comment]
This task will likely need to be replaced with multiple others, as there is a small handful of related issues here:

- onlpdump has been replaced with onlps, this is potentially related to which onlp version. In any case, if onlps works, then we are okay. 
- onlpdump.py appears to be used for testing purposes, we need to determine if it's appropriate for all cases. 
- onlpdump.service does not appear to be be anywhere in ONL, however, there is a daemon, onlpd, which isn't making it onto the images, which (1) needs to be setup, and (2) we will need to be setting up onlpd.service. I've begun the work here, and will continue after the 2021.03 release. 

In any case, these issues will be addressed in the near future, but for now I'm moving this over to backlog until after upcoming release.

**Comment by toganlabs** [comment]
Fixed in https://github.com/NetworkGradeLinux/meta-mion/commit/a0a01d9336b115543c661832c306888bac26fcfd
