### ISSUE TITLE
Quality of Life Improvements

### ISSUE THREAD

**Issue by CommitThis** [NetworkGradeLinux/meta-mion#81]
Some things we could do to improve the quality of life on usability (all based on personal opinion, of course)

* Set `alias ll="ls -lh --group-directories-first"` or something similar in `/etc/profile` or somewhere....
* add `vim`
* `git` (although granted, this may be out of scope for a deployable OS)
* `dmidecode`. This would be useful to QA in verifying installed BIOS version
* PROMPT theming. Ok this one is a little silly, but might be nice if we can tie in mion colours with the OS
* Add a _mion_ release file with the build and release name in `/etc/mion-release` or similar

There may be others, and would like to see if anyone else had others in mind, or if they had any objection to this.

**Comment by johntoomey** [comment]
vim is in the default (core) image and git is in the dev image.
dmidecode will be moved back here: https://github.com/NetworkGradeLinux/meta-mion/pull/93. 
The mion release info is in /etc/os-release. 
Moving the other two bash related ones into the bach config task here: https://github.com/NetworkGradeLinux/meta-mion/issues/88
